books/urls.py
from django.conf.urls.defaults import *
from django.contrib.auth.decorators import login_required
from django.conf.urls import patterns, url
from django.views.generic import RedirectView, TemplateView
from tastypie.api import Api
from books.views import *
from books.api import PassageApiDetail, PassageListApi, DictionaryListApi

urlpatterns = patterns('',
    url(r'(?P<slug>[\w-]+)/text$', ChapterListView.as_view(), name='books.table_of_contents'),
    url(r'moby-dick/text/(?P<slug>[\w-]+)$', ChapterView.as_view(), name='books.chapter'),
    url(r'^api/dictionary/(?P<word>[\w-]+)$', DictionaryListApi.as_view()),
    url(r'^highlights/create', login_required(CreateHighlight.as_view()), name='books.highlight.create'),
    url(r'^highlights/search$', SearchHighlightListView.as_view(), name='books.highlight.search'),
    url(r'^highlights/random$', RandomHighlightView.as_view(), name='books.highlight.random'),
    url(r'^highlight/(?P<pk>[0-9]+)/like$', like_highlight, name='books.highlight.like'),
    url(r'lists/$', BookListView.as_view(), name='books.list'),
    url(r'(?P<slug>[\w-]+)$', BookDetailView.as_view(), name='books.detail'),
    url(r'^highlights/', HighlightListView.as_view(), name='books.highlight.list'),
    url(r'^dictionary/$', TemplateView.as_view(template_name="books/dictionary.html"), name='books.dictionary'),
    #url(r'^api/passages/$', PassageListApi.as_view()),
    #url(r'^api/passage/(?P<pk>[0-9]+)/$', PassageApiDetail.as_view()),
)

lists/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView
from books.views import *

urlpatterns = patterns('',
    url(r'item/(?P<id>\d+)/move-up$', 'lists.views.move_item_up', name='move_item_up'),
    url(r'item/(?P<id>\d+)/move-down$', 'lists.views.move_item_down', name='move_item_down'),
)

books/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import Q, F
from django.template.defaultfilters import slugify
from django.utils import timezone
from datetime import datetime
import json
import re

from .managers import HighlightManager
from .google import GoogleBookQuery, GoogleBook


class Author(models.Model):
    """ The authors, who write the books. """
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,
                            help_text='Unique URL created for each author.')
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = timezone.now()
        super(Author, self).save(*args, **kwargs)

    class Meta:
        ordering = ['last_name', 'first_name']

    @models.permalink
    def get_absolute_url(self):
        return ('books.views.author.show', (), {'author_slug': self.slug})

    def __unicode__(self):
        return "%s %s" % (self.first_name, self.last_name)


class Book(models.Model):
    """ The books I read. """
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique URL created for each book.')
    isbn10 = models.CharField(max_length=10, blank=True)
    isbn13 = models.CharField(max_length=13, blank=True)
    extra = models.TextField(null=True, blank=True, help_text='Google Books API query results for the book (JSON)')
    created_at = models.DateTimeField()
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        """ Save this book. """
        if self.created_at is None:
            self.created_at = timezone.now()

        if self.slug == '':
            self.slug = slugify(self.title)

        super(Book, self).save(*args, **kwargs)

    def recent_highlight(self):
        """ Return the most recent highlight for this book. """
        if self.passage_set.all().count() == 0:
            return None
        return self.passage_set.all()[0]

    def google(self):
        if not self.extra:
            if self.isbn13:
                query = GoogleBookQuery.by_isbn(self.isbn13)
                self.extra = query.get_result()
                self.save()

        if self.extra:
            return GoogleBook(self.extra)
        else:
            return None

    def _query_google_book(self):
        query = GoogleBookQuery.by_isbn(self.isbn13)
        self.extra = query.get_result()

    class Meta:
        ordering = ['title']

    @models.permalink
    def get_absolute_url(self):
        return ('books.views.book.show', (), {'book_slug': self.slug})

    def __unicode__(self):
        return self.title

    @staticmethod
    def create_by_isbn13(isbn):
        query = GoogleBookQuery.by_isbn(isbn)
        json = query.get_result()
        gbook = GoogleBook(json)
        book = Book(title=gbook.title(), isbn13=isbn)
        author, result = Author.objects.get_or_create(
                            first_name=gbook.author_fname(),
                            last_name=gbook.author_lname())
        book.author = author
        book.extra = json
        book.save()
        return book


class Passage(models.Model):
    """ A passage from a book or short story. """
    MANUAL_ENTRY = 1
    KINDLE_CLIP = 2

    SOURCES = (
        (MANUAL_ENTRY, 'Manual Entry'),
        (KINDLE_CLIP, 'Kindle'),
    )

    book = models.ForeignKey(Book)
    context = models.CharField(max_length=255, blank=True)
    text = models.TextField()
    location = models.CharField(max_length=100, blank=True)
    source = models.IntegerField(choices=SOURCES, default=MANUAL_ENTRY)
    created_at = models.DateTimeField()
    likes = models.IntegerField(default=1)
    last_liked = models.DateTimeField(null=True)

    objects = HighlightManager()

    def save(self, *args, **kwargs):
        """ On save, update timestamps. """
        if self.created_at is None:
            self.created_at = timezone.now()
        if self.last_liked is None:
            self.last_liked = self.created_at

        super(Passage, self).save(*args, **kwargs)

    @staticmethod
    def search(query):
        """ A very simple search for text within a passage. """
        if query:
            return Passage.objects.filter(
                        Q(text__icontains=query) |
                        Q(book__title__icontains=query) |
                        Q(book__author__last_name__icontains=query))
        else:
            return []

    def like(self):
        self.likes = F('likes') + 1
        self.last_liked = timezone.now()
        self.save()

    class Meta:
        ordering = ['-created_at']

    def __unicode__(self):
        return self.text[:50]


class Chapter(models.Model):
    book = models.ForeignKey(Book)
    name = models.CharField(max_length=250)
    position = models.IntegerField(unique=True)
    slug = models.SlugField(max_length=250, unique=True)

    class Meta:
        ordering = ['position']
            
    @models.permalink
    def get_absolute_url(self):
        return ('books.chapter', (), {'slug': self.slug})
    
    def __unicode__(self):
        return "%s" % (self.name)

    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.name)
        super(Chapter, self).save(*args, **kwargs)


class Paragraph(models.Model):
    chapter = models.ForeignKey(Chapter)
    text = models.TextField()
    position = models.IntegerField()
    
    class Meta:
        ordering = ['chapter', 'position']

    def __unicode__(self):
        return "%s" % (self.text[:75])

lists/models.py
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models import Max
from django.db import transaction
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

class ItemList(models.Model):
    """ Represents an ordered list of model objects """
    
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True,
                            help_text='Unique URL created for each book list.')
    created_at = models.DateTimeField(default=None)
    
    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = timezone.now()
        super(ItemList, self).save(*args, **kwargs)

    def next_position(self):
        results = self.items.all().aggregate(Max('position'))
        curmax = results.get('position__max', 0)
        if curmax is None:     
            return 1
        else:
            return curmax + 1
 
    def __unicode__(self):
        return self.name


class Item(models.Model):
    """ A model object that exists within an ItemList. """
    content_type = models.ForeignKey(ContentType,
            verbose_name=_('content_type'),
            related_name="content_type_set_for_%(class)s")
    object_pk = models.TextField(_('object ID'))
    content_object = generic.GenericForeignKey(ct_field="content_type", fk_field="object_pk")
    item_list = models.ForeignKey(ItemList, related_name="items")
    position = models.IntegerField(default=None, blank=True)
    created_at = models.DateTimeField(default=None, blank=True)

    class Meta:
        ordering = ['position']

    def save(self, *args, **kwargs):
        if self.created_at is None:
            self.created_at = timezone.now()

        if self.position is None:
            self.position = self.item_list.next_position()

        super(Item, self).save(*args, **kwargs)

    def delete (self):
        items_below = self.item_list.items.filter(position__gt=self.position)
        items_below.update(position = models.F('position') - 1)
        super(Item, self).delete()

    @transaction.commit_on_success 
    def move_to_position(self, new_position):
        """ Move an item to the given position.  Updates the position of
            other items in the list affected by the move.  Raises an
            IndexError if position is outside the list boundary.  
        """
        max_position = self.item_list.items.count()
        in_range = new_position >= 1 and new_position <= max_position
        if in_range:
            current = self.position
            queryset = self.item_list.items.exclude(pk=self.pk)
            if new_position > current:
                queryset = queryset.filter(position__gt=current,
                                           position__lte=new_position)
                queryset.update(position = models.F('position') - 1)
            else:
                queryset = queryset.filter(position__lt=current,
                                           position__gte=new_position)
                queryset.update(position = models.F('position') + 1)

            self.position = new_position
            self.save()
        else:
            raise IndexError("Position is out of range.")

    def move_up(self):
        """ Move this item up one position in the list. """
        self.move_to_position(self.position - 1)

    def move_down(self):
        """ Move this item down one position in the list. """
        self.move_to_position(self.position + 1)

    @models.permalink
    def get_move_up_url(self):
        return ('move_item_up', (), {'id': self.id})

    @models.permalink
    def get_move_down_url(self):
        return ('move_item_down', (), {'id': self.id})

    def __unicode__(self):
        return str(self.content_object) 

books/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Passage


class PassageForm(ModelForm):
    location = forms.CharField(required=False,
                widget=forms.TextInput(attrs={'placeholder': 'location'}))
    text = forms.CharField(
                widget=forms.Textarea(attrs={'placeholder': 'highlighted text'}))

    class Meta:
        model = Passage
        fields = ('book', 'location', 'text')
        #widgets = {
        #    'name': Textarea(attrs={'cols': 80, 'rows': 20}),
        #}

books/views.py
# Create your views here.
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.utils import timezone
from django.utils.html import escape
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView
from .models import Author, Book, Passage, Chapter
from .forms import PassageForm
from lists.models import ItemList


class BookDetailView(DetailView):

    model = Book
    template_name = "books/book_detail.html"

    def get_object(self):

        if 'slug' in self.kwargs:
            slug = escape(self.kwargs.get('slug'))
            return get_object_or_404(Book, slug=slug)


class BookListView(TemplateView):
    """ Displays the book list in a condensed table. """
    template_name = "books/lists.html"

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        context['to_read'] = get_object_or_404(ItemList, slug="to-read")
        context['now_reading'] = get_object_or_404(ItemList, slug="now-reading")
        context['have_read'] = get_object_or_404(ItemList, slug="have-read")
        context['favorites'] = get_object_or_404(ItemList, slug="favorites")
        return context


class HighlightListView(ListView):

    model = Passage

    template_name = 'books/passage_list.html'

    def get_context_data(self, **kwargs):
        context = super(HighlightListView, self).get_context_data(**kwargs)
        return context

    def get(self, request, *args, **kwargs):
        self.query = None
        self.form = PassageForm()

        passages = Passage.objects.top_rated()
        page = request.GET.get('page')
        self.object_list = self.paginate(passages, page)

        context = self.get_context_data(object_list=self.object_list, query=self.query, form=self.form)

        return self.render_to_response(context)

    def paginate(self, all_passages, page):
        paginator = Paginator(all_passages, 40)

        try:
            passages = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            passages = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            passages = paginator.page(paginator.num_pages)

        return passages


class SearchHighlightListView(HighlightListView):

    def get(self, request, *args, **kwargs):
        if 'q' in request.GET:
            self.query = escape(request.GET['q'])
            search_results = Passage.search(self.query)
            page = request.GET.get('page')
            self.object_list = self.paginate(search_results, page)
        else:
            self.object_list = []

        context = self.get_context_data(object_list=self.object_list, query=self.query)

        return self.render_to_response(context)


class RandomHighlightView(DetailView):

    model = Passage
    template_name = 'books/passage_random.html'
    context_object_name = 'passage'

    def get_object(self):
        object = Passage.objects.random().get()
        return object


class CreateHighlight(CreateView):
    form_class = PassageForm
    template_name = 'books/passage_create.html'
    success_url = reverse_lazy('books.highlight.list')


class ProtectedView(TemplateView):
    template_name = 'secret.html'

    def dispatch(self, *args, **kwargs):
        return super(ProtectedView, self).dispatch(*args, **kwargs)


class ChapterListView(ListView):
    model = Chapter
    template_name = 'books/table_of_contents.html'


class ChapterView(DetailView):
    model = Chapter
    template_name = 'books/chapter.html'
    context_object_name = 'chapter'

@login_required
def like_highlight(request, pk):
    """ Move the item up one position in the list. """
    passage = get_object_or_404(Passage, pk=pk)
    passage.like()
    return redirect(request.META.get('HTTP_REFERER', None))

lists/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect, get_object_or_404
from lists.models import Item


def check_user_allowed(user):
    return user.is_authenticated()


@user_passes_test(check_user_allowed)
def move_item_up(request, id):
    """ Move the item up one position in the list. """
    item = get_object_or_404(Item, pk=id)
    item.move_up()
    return redirect(request.META.get('HTTP_REFERER', None))


@user_passes_test(check_user_allowed)
def move_item_down(request, id):
    """ Move the item down one position in the list. """
    item = get_object_or_404(Item, pk=id)
    item.move_down()
    return redirect(request.META.get('HTTP_REFERER', None))


@user_passes_test(check_user_allowed)
def move_item_to_list(request, id, list_id):
    item = get_object_or_404(Item, pk=id)
    list = get_object_or_404(ItemList, pk=list_id)

    # Add item to the top of the given list
    list.items.create(content_object = item.content_object,
                      position = 1)

    item.delete()
    

books/templates/books/base.html
{% extends "base.html" %}

{% load active %}

{% block nav.h %}
    class="{% active request 'highlights' %}"
{% endblock %}

{% block nav.r %}
    class="{% active request 'lists' %}"
{% endblock %}

books/templates/books/book_detail.html
{% extends "books/base.html" %}

{% load humanize %}

{% block pageheader %}
    {% if object.google %}
        <a class="pull-left" href="{{ object.google.info_link }}" style="margin-right: 20px;margin-bottom: 10px;">
            <img class="media-object" src="{{ object.google.thumbnail }}" alt="{{ object.title }}">
        </a>
    {% endif %}
    <h2 class="page-title">
        {{ object.title }} 
        <small class="muted"><strong>by {{object.author }}</strong></small>
    </h2>
{% endblock %}
{% block lead %}
    {% if object.google %} 
        {% with object.google as google %}
            <div class="row-fluid">
                <p class="lead">
                    {{ google.description|striptags }}
                    (<a href="{{ google.info_link }}">more info</a>)
                </p>
            </div>
        {% endwith %}
    {% endif %}
{% endblock %}

{% block content %}
    {% with object.passage_set.all as passages %}
        {% if passages.count %}
            <div id="box-container">
                {% for passage in object.passage_set.all  %}
                    {% include "books/passage_detail.html" %}
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endblock %}

books/templates/books/book_table.html
{% load humanize %}

<div class="row-fluid">
    <div class="span12">
        <h4>{{ list.name }}</h4>
        <table class="table">
          <tbody>
          {% for item in list.items.all %}
              <tr>
                  <td style="width: 24px;">
                      {% if item.content_object.google.small_thumbnail %}
                        <div style="width: 24px; height: 37px;">
                          <img src="{{ item.content_object.google.small_thumbnail }}" alt="img"/>
                        </div>
                      {% endif %}
                  </td>
                  <td>
                      <strong>
                          <a href="{% url books.detail item.content_object.slug %}">{{ item.content_object.title }}</a>
                      </strong>
                  </td>
                  <td>
                      <strong>
                           <strong class="muted">{{ item.content_object.author.last_name }}</strong>
                      </strong>
                  </td>
              </tr>
          {% endfor %}
          </tbody>
        </table>
    </div>
</div>

books/templates/books/chapter_detail.html
{% extends "books/base.html" %}

{% block extra_javascript %}
    <script>

      $(document).ready(function() {  
        $('p').mouseup( function () {
          var selection = getSelectedText();
          var text = String(selection);
          var parent = selection.anchorNode.parentNode;
          Hermes.define(text, $(parent));
        });
       });

      function getSelectedText() {
          var selection;
          if (window.getSelection) {
              selection = window.getSelection();
          } else if (document.selection) {
              selection = document.selection.createRange();
          }
          return selection;
      }

    </script>

{% endblock %}

{% block pageheader %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="span8">
            <div class="book">
                <ul class="breadcrumb">
                    <li><a href="{% url books.table_of_contents 'moby-dick'%}">Moby Dick</a> <span class="divider">/</span></li>
                    <li class="active">{{ chapter.name }}</li>
                </ul>
                {% for paragraph in chapter.paragraph_set.all %}
                    <p id="paragraph-{{ paragraph.id }}">{{ paragraph.text }}</p>
                {% endfor %}
            </div>
        </div>
        <div span="span4">
            
        </div>
    </div>
{% endblock %}

books/templates/books/dictionary.html
{% extends "base.html" %}

{% block extra_javascript %}
    <script type="text/javascript"> 
        $(document).ready(function() {
            $("#word").change(function(e) {
                var form = $('#search-form'); 
                var url = form.attr('action') + this.value;
                $.ajax({
                  url: url,
                  method: 'GET',
                  success: function(data) {
                    var json = eval(data);
                    $('#results').empty();
                    for (var i = 0; i < json.length; i++) {
                        var definition = json[i];
                        $('#results').append('<li>' + definition.text + '</li>');
                    }
                    if (json.length == 0)
                        $('#results').append('<li><em>Not found</em></li>');
                  },
                  error: function(data, statusCode) {
                    alert("ERROR: "+data)
                  }
                });
            });
            $("#word").focus();
            $("#word").focus(function() { $(this).select() });
            $("#word").mouseup(function(e) { e.preventDefault(); });
        });
      

    </script>
{% endblock %}

{% block content %}
    <h3>Dictionary</h3>
    <form id="search-form" action="/book/api/dictionary/" method="post">
        <label for="word">Search</label>
        <input id="word" name="word" type="text" class="input-large"/>
    </form>
    <ul id="results">
    </ul>
{% endblock %}

books/templates/books/lists.html
{% extends "books/base.html" %}

{% load humanize %}

{% block pageheader %}
    <h3>Reading Lists</h3>
{% endblock %}
{% block content %}
    <div id="box-container">
        <div class="box photo col3 masonry-brick">
            {% include "books/book_table.html" with list=now_reading %} 
        </div>
        <div class="box photo col3">
            {% include "books/book_table.html" with list=to_read %} 
        </div>
        <div class="box photo col3">
            {% include "books/book_table.html" with list=have_read %} 
        </div>
        <div class="box photo col3">
            {% include "books/book_table.html" with list=favorites %} 
        </div>
    </div>
{% endblock %}

books/templates/books/passage_comment.html
{% load comments %}

{% if passage %}
    {% get_comment_list for passage as comment_list %}
    {% if comment_list %}
        <div class="well">
        {% for comment in comment_list %}
            <div style="padding-bottom: 0px;">
                <strong class="muted">
                    <span style="color:green;">{{ comment.user.username }}</span>
                </strong>
                <span class="comment">
                    - {{ comment.comment }}
                </span>
            </div>
        {% endfor %}
        </div>
    {% endif %}
    {% if request.user.is_authenticated %}
        <a id="add-comment-{{ passage.id }}" class="add-comment"><strong class="muted">add comment</strong></a>
        <div id="add-comment-{{ passage.id }}-form" class="comment-form welly">
            {% get_comment_form for passage as form %}
            <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form.comment }}
                {{ form.honeypot }}
                {{ form.content_type }}
                {{ form.object_pk }}
                {{ form.timestamp }}
                {{ form.security_hash }}
                <input type="hidden" name="next" value="{{ request.path }}" />
                <input type="submit" value="Add comment" id="id_submit" class="btn" />
            </form>
        </div>
    {% endif %}
{% endif %}

books/templates/books/passage_create.html
{% extends "books/base.html" %}

{% block pageheader %}
    <h3>Add a highlight</h3>
{% endblock %}

{% block content %}
<div class="content"> 
        <p>
            <form class="form" method="post" action="{% url books.highlight.create %}">
              <fieldset>
                {% csrf_token %}
                {{ form.non_field_errors }}
                <label for="id_book">Book</label>
                {{ form.book }}
                {{ form.book.errors }}
                {{ form.location }}
                {{ form.location.errors }}
                {{ form.text }}
                {{ form.text.errors }}
                <input type="submit" value="Add this highlight" class="btn btn-primary"/>
              </fieldset>
            </form>
        </p>
</content>
{% endblock %}

books/templates/books/passage_detail.html
  <div class="box photo col3 masonry-brick">
      {% include "books/passage_text.html" %} 
  </div>

books/templates/books/passage_list.html
{% extends "books/base.html" %}

{% block pageheader %}
    {% if request.user.is_authenticated %} 
        <a href="{% url books.highlight.create %}" class="btn btn-primary btn-small pull-right add-highlight"><i class="icon-plus icon-white"></i> Add Highlight</a>
    {% endif %}
            <form action="{% url books.highlight.search %}" method="get" class="pull-right" >
                <div class="input-append">
                    <input type="text" name="q" class="input-medium">
                    <input type="submit" class="btn" value="Search">
                </div>
            </form>
    <h3>Highlights from classic literature</h3>
{% endblock %}

{% block content %}
    {% if object_list %}
        <div id="box-container">
            {% for passage in object_list %}
                {% include "books/passage_detail.html" %}
            {% endfor %}
        </div>
        <div class="pagination pagination-small pagination-centered" style="margin-top: 10px; margin-bottom: 20px;">
            <ul>
                {% if object_list.has_previous %}
                    <li><a href="?q={{ query }}&amp;page={{ object_list.previous_page_number }}">{{ "<<" }}</a></li>
                {% endif %}
                {% for i in object_list.paginator.page_range %}
                    {% if i < 20 %}
                    {% if object_list.number == i %}
                        <li class="active"><a href="?page={{i}}">{{i}}</a></li>
                    {% else %}
                        <li><a href="?q={{query}}&amp;page={{i}}">{{i}}</a></li>
                    {% endif %}
                    {% endif %}
                {% endfor %}
                {% if object_list.has_next %}
                    <li><a href="?q={{query}}&amp;page={{ object_list.next_page_number }}">{{ ">>" }}</a></li>
                {% endif %}
            </ul>
        </div>
    {% else %}
        <p>No passages found.</p>
    {% endif %}
{% endblock %}

books/templates/books/passage_random.html
{% extends "books/base.html" %}

{% block page-title %} Random quote {% endblock %}

{% block quote-random %}
    <li class="active"><a href="{% url quote.random %}">Random</a></li>
{% endblock %}
    
{% block content %} 
    {% include "books/passage_detail.html" %}
    <div class="row-fluid">
        <div class="span12">
            <a href="{% url books.highlight.random %}" class="btn btn-primary">Next Highlight</a>
        </div>
    </div>
{% endblock %}

books/templates/books/passage_text.html
{% load humanize %}
{% load highlight %}

<div class="quote">
    <div class="text">
        {% if query %}
            "{{ passage.text|highlight:query }}"
        {% else %}
            "{{ passage.text }}"
        {% endif %}
    </div>
    <div class="title" >
        <strong>
            <a href="{% url books.detail passage.book.slug %}">
                - {{ passage.book }} by {{ passage.book.author}}
            </a>
        </strong>
    </div>
    {% include "books/passage_comment.html" %}
    {% if request.user.is_authenticated %}
        <form action="{% url books.highlight.like passage.id %}" method="post" class="pull-right" style="margin-bottom: 0;">
            {% csrf_token %}
            <button class="btn btn-mini">
                <i class="icon-thumbs-up"></i>
                {{ passage.likes }}
            </button>
        </form>
    {% endif %}
</div>

books/templates/books/table_of_contents.html
{% extends "books/base.html" %}

{% block pageheader %}
    <h3>Moby Dick by Herman Melville</h3>
{% endblock %}
{% block content %}
    <ul>
        {% for chapter in object_list %}
            <li><a href="{{chapter.get_absolute_url}}">{{ chapter.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}